---

- name: Set up the servers
  hosts:
    - localhost
  roles:
    - ssh_key
    - nodes_configuration
    - role: nodes
      when: not (skip_nodes_setup | default(false) | bool)
    - nodes_ssh_keys

- name: Set up the Percona XtraDB clusters
  hosts:
    - percona
  roles:
    - nodes_firewall
    - nodes_percona_cluster
