---

- name: "Check if the SSH service's port is open on percona_cluster_node }}"
  ansible.builtin.wait_for:
    host: "{{ hostvars[percona_cluster_node]['ansible_host'] }}"
    port: "{{ hostvars[percona_cluster_node]['ansible_ssh_port'] }}"
    state: started
    search_regex: '^SSH-\d+\.\d+-.+$'
    delay: 0
    timeout: 300

- name: "Get the SSH key of percona_cluster_node }}"
  ansible.builtin.command:
    cmd: |-
      ssh-keyscan
      -t ssh-ed25519
      -p {{ hostvars[percona_cluster_node]['ansible_ssh_port'] | quote }}
      {{ hostvars[percona_cluster_node]['ansible_host'] | quote }}
  changed_when: false
  register: result

- name: Update the known_hosts file
  ansible.builtin.known_hosts:
    path: "{{ ssh_known_hosts_file }}"
    key: "{{ key }}"
    name: "{{ hostvars[percona_cluster_node]['ansible_host'] }}"
    hash_host: yes
  loop: "{{ result.stdout_lines }}"
  loop_control:
    loop_var: key
